### ISSUE TITLE
Will CacheSleeve implement new StackExchange.Redis ?

### ISSUE THREAD

**Issue by khorvat** [jdehlin/CacheSleeve#1]
Is there any plans to implement StackExchange.Redis support into CacheSleeve ? Async support will be great ?

Thanks

**Comment by jdehlin** [comment]
If there's interest in those two things I would be happy to implement them. Are you currently using CacheSleeve, or would you be interested in using it if had Async support?

**Comment by khorvat** [comment]
We are considering Hybrid Cache as we have performance issues under heavy load, we are using too much resources on serialization and Redis so hybrid seems like a way to go. Mark Gravell also mentioned that they are using the same thing on StackExchange even mentioned that they will maybe release hybrid solution as open source. 

So we are using StackExchange.Redis in Async mode and would like to try CacheSleeve in Async too.

**Comment by jdehlin** [comment]
Cool. I should be able to look into that soon.

**Comment by khorvat** [comment]
Great thanks.

**Comment by jdehlin** [comment]
I've migrated the library to use StackExchange.Redis and added Async support for all caching methods. There are probably some other features of SE.Redis that could be taken advantage of but this should be a good start. 

I haven't had a chance to test this is the real world yet but all of the tests are passing. I will be deploying this to a large project next week. If you have any further issues or have any other features you would like to see incorporated please let me know.

Also, how did you find CacheSleeve?

**Comment by khorvat** [comment]
Yes Async is great to start with, we will try to test everything early next week and get back to you. I have found CacheSleeve by searching for old Mark Gravell 2-tire hybrid cache comment as I was hopping that he shared his StackOverflow code with the community. Then I ended up at your repository :). 

I'll get back to you as soon as we test everything. Do you accept merge requests (in case we find and fix few things) ?

**Comment by jdehlin** [comment]
Thanks for offering to test it out. I would be happy to accept merge requests if find any issues.

**Comment by INeedADip** [comment]
Just ran across this.  This is the exact problem I'm trying to solve.  Do you plan on updating the NuGet at any point, or should I download/compile/reference it?

Looks like great work, I'm excited to give it a test run.

**Comment by jdehlin** [comment]
I can probably update the NuGet package this weekend. I'll post back here when it's up.

**Comment by khorvat** [comment]
Hi, we have tried to use CacheSleeve in our project but it turns out that there are few things that are stopping us from using it. What we need is the hybrid provider that will be able to check for key in-memory and if not found try to fetch the key from Redis. 

This is our desired architecture, is this something that CacheSleeve should have down the road ?

**Comment by jdehlin** [comment]
A new version of the NuGet package has been released with StackExchange.Redis and Async support.

**Comment by khorvat** [comment]
Hi, I just saw that you closed this issue and I wanted to updated you with our progress few weeks but have been busy. However we successfully implemented cachesleeve in our app but with some minor and major changes. Right now we are at the beta testing phase and I'll probably confirm that everything is working properly in a month or two (We have made extensive testing and it seems ok but can't be 100% sure). We needed to extend few of the classes and abstract a few in order to be more flexible for kicking our stuff in. If you are interested in merging or porting few of the things and need help let us know, you can find the changes in one of your forks: https://github.com/MonoSoftware/CacheSleeve (I'll check with a colleague if he pushed everything to GitHub).

Thanks again.

**Comment by jdehlin** [comment]
That's great! Very glad you were able to get it implemented in your project. I will review the changes in the fork soon. Thanks for making your changes available.

**Comment by jdehlin** [comment]
I liked the changes you guys made and incorporated almost all of them back in to the project. There was only one I had trouble with: (https://github.com/MonoSoftware/CacheSleeve/commit/a40a45d346fea40ef3bd56ba21f6f13d91fa091b). When I upgraded xUnit it caused most of the tests to fail.

As I said, almost all of your changes are now in the library so you could switch back to using the main branch rather than maintaining your own fork if you wanted to.

Thanks again!
