### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by barankaynak** [jdehlin/CacheSleeve#3]
New version is not working when I update library from 1.3.10 to 1.4.7. Can you please help me?

Timeout performing DEL cs.xxxx, inst: 1, mgr: ExecuteSelect, queue: 18, qu=0, qs=18, qc=0, wr=0/0, in=0/0

StackExchange.Redis.ConnectionMultiplexer.ExecuteSyncImpl(Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\ConnectionMultiplexer.cs:1824
   StackExchange.Redis.RedisBase.ExecuteSync(Message message, ResultProcessor`1 processor, ServerEndPoint server) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisBase.cs:81
   StackExchange.Redis.RedisDatabase.KeyDelete(RedisKey key, CommandFlags flags) in c:\TeamCity\buildAgent\work\3ae0647004edff78\StackExchange.Redis\StackExchange\Redis\RedisDatabase.cs:368
   CacheSleeve.RedisCacher.Remove(String key) in c:\Users\Jonathan\Projects\Personal\CacheSleeve\CacheSleeve.NET40\RedisCacher.cs:91
   CacheSleeve.HybridCacher.Set(String key, T value, DateTime expiresAt, String parentKey) in c:\Users\Jonathan\Projects\Personal\CacheSleeve\CacheSleeve.NET40\HybridCacher.cs:69

**Comment by jdehlin** [comment]
Are you getting this error consistently or is it intermittent?

**Comment by barankaynak** [comment]
Consistently

**Comment by jdehlin** [comment]
My first guess was a connection issue but that results in a different exception: No connection is available to service this operation.

I'm using this library currently in a large scale project without any timeout issues. Maybe try some of these suggestions: http://azure.microsoft.com/blog/2015/02/10/investigating-timeout-exceptions-in-stackexchange-redis-for-azure-redis-cache/

You can also try using just StackExchange.Redis and see if that times out. That would narrow down if it's a problem with Redis in general or with the CacheSleeve library.

**Comment by jdehlin** [comment]
Were you able to narrow down the issue any?

**Comment by barankaynak** [comment]
I think I should change the timout value of ConnectTimeout prop from ConfigurationOptions. Is there any web.config element that I can change it on this project? Thanks.

**Comment by jdehlin** [comment]
I will make that an option. I'll post back here when it's available.

**Comment by jdehlin** [comment]
Sorry for the delay. A new version of the library is up on NuGet. You can now pass in the timeout as a parameter to Init. Let me know if there's anything more I can do to help
