### ISSUE TITLE
Debug setting overwritten

### ISSUE THREAD

**Issue by robodroid** [jdehlin/CacheSleeve#7]
If you disable debugging like so:

```
CacheSleeve.CacheManager.Init("localhost);
CacheSleeve.CacheManager.Settings.Debug = false;
```

The setting will be overwritten if you do something like this:

```
var localCache = new HttpContextCacher();
localCache.Set("key", "test", new TimeSpan(1000));
```
It appears the initializer for HttpContextCacher and RedisCacher are setting Debug = true;
Shouldn't they honor the setting in CacheManager.Settings?

**Comment by jdehlin** [comment]
They should respect whatever is set on the CacheManager. Would you like to submit a pull request to fix the issue?

**Comment by snavarropino** [comment]
I have created a pull request in order to fix it

**Comment by jdehlin** [comment]
Merged. Thanks.
